---
title: "NYC Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```

```{r}
data(rest_inspec)

set.seed(3)

rest_inspec = 
  rest_inspec %>%
  janitor::clean_names() %>% 
    filter(boro == "MANHATTAN") %>%
  sample_n(5000) %>% 
  mutate(zipcode = factor(zipcode)) %>% view

```

Column {data-width=650}
-----------------------------------------------------------------------

### Inspection Scores & Inspection Dates

```{r}
rest_inspec %>%
  plot_ly(x = ~inspection_date, y = ~score, 
          type = "scatter", mode = "markers",
          alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Inspection Scores & Violation Types

```{r}
common_vio =
  rest_inspec %>% 
  count(violation_description, sort = TRUE) %>% 
  top_n(8) %>% 
  select(violation_description)

inner_join(rest_inspec, common_vio, by = "violation_description") %>% 
  plot_ly(y = ~score, color = ~violation_description, type = "box",
          colors = "Set2")
```



### Top Types of Cuisine in Manhattan

```{r}

common_cuis =
  rest_inspec %>% 
  count(cuisine_description, sort = TRUE) %>% 
  top_n(8) %>% 
  select(cuisine_description)

inner_join(rest_inspec, common_cuis, by = "cuisine_description") %>% 
  count(cuisine_description) %>%
  plot_ly(x = ~cuisine_description, y = ~n, type = "bar")
```
