---
title: "Plotly Examples"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
  
---

My name is Alexis and I madke websites with _interactive graphics_!

```{r, message=FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```



## Let's make some plots


```{r}
data("nyc_airbnb")
```


```{r}
set.seed(1)

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)  %>% 
  sample_n(5000)
```

Scatterplot
```{r}
nyc_airbnb %>%
  plot_ly(x = ~lat, y = ~long, type = "scatter", mode = "markers",
          color = ~price, alpha = 0.5)
```

Boxplot
```{r}
nyc_airbnb %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
```

Barchart
```{r}
nyc_airbnb %>%
  count(neighbourhood) %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>%
  plot_ly(x = ~neighbourhood, y = ~n, type = "bar")
```

